apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: sxatqgabg-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/sxatqgabg-java-springboot-gitops